core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path("", include('pages.urls')),
    path('', admin.site.urls),
]

pages/urls.py
from django.urls import path

from .views import HomePageView,VendaPageView, RelatorioPageView

app_name = 'pages'

urlpatterns = [
    path("imoveis",HomePageView.as_view(), name='imoveis'),
    path("venda/<int:id_imovel>",VendaPageView.as_view(), name='venda'),
    path("relatorio/<int:id_venda>",RelatorioPageView.as_view(), name='relatorio')
]

cliente/models.py
from django.db import models

class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=True)
    
    def get_by_id(self, id):
        return self.filter(id=id).get()

class Cliente(models.Model):

    STATUS = [
        (True,'Ativo'),
        (False,'Inativo')
    ]

    nome = models.CharField(name='nome',verbose_name='Nome',max_length=255)
    email = models.EmailField(name='email',verbose_name='Email',unique=True,db_index=True,max_length=255)
    cpf = models.CharField(name='cpf',verbose_name='CPF',unique=True,db_index=True,max_length=14)
    telefone = models.CharField(name='telefone',verbose_name='Telefone',max_length=15)
    dtainclusao = models.DateField(name='dtainclusao',verbose_name='Data Cadastro',auto_now_add=True)
    status = models.BooleanField(name='status',verbose_name='Status',choices=STATUS) 

    available = AvailableManager()
    
    class Meta():
        ordering = ('nome','dtainclusao',)

    def __str__(self) -> str:
        return self.nome

imovel/models.py
from django.db import models

class AvailableManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=True)
    
    def get_by_id(self, id):
        return self.filter(id=id).get()


class Imovel(models.Model):
    STATUS = [
        (True,'Ativo'),
        (False,'Inativo')
    ]

    TIPO = [
        ('APARTAMENTO','Apartamento'),
        ('LOTE','Lote')
    ]

    descricao = models.CharField(verbose_name='Descrição', max_length=255)
    endereco = models.CharField(verbose_name='Endereço',max_length=255)
    valor_imovel = models.DecimalField(verbose_name='Valor do Imovel', max_digits=10, decimal_places=2)
    data_inclusao = models.DateField(verbose_name='Data Cadastro', auto_now_add=True)
    tipo = models.CharField(verbose_name='Tipo', max_length=11, choices=TIPO)
    status = models.BooleanField(verbose_name='Status', choices=STATUS)
    
    objects = models.Manager()
    available = AvailableManager()

    class Meta():
        ordering = ('descricao','valor_imovel',)

    def __str__(self) -> str:
        return self.descricao

    @property
    def comissao(self):
        return float(self.valor_imovel) * 0.05
    

pages/models.py
from django.db import models

# Create your models here.

venda/models.py
from django.db import models


CONDICOES_PAGTO_CHOICES = [
    (1, 'À vista'),
    (180, '180x')    
]


class Venda(models.Model):

    imovel = models.ForeignKey('imovel.Imovel', on_delete=models.SET_NULL, verbose_name='Imovel', blank=False, null=True, related_name='vendas')
    vendedor =  models.ForeignKey('vendedor.Vendedor',on_delete=models.SET_NULL,verbose_name='Vendedor',blank=False,null=True, related_name='vendas')
    cliente =  models.ForeignKey('cliente.Cliente',on_delete=models.SET_NULL,verbose_name='Cliente',blank=False,null=True, related_name='vendas')
    data_inclusao = models.DateField(verbose_name='Data Cadastro',auto_now_add=True)
    condicao_pagto = models.IntegerField(verbose_name='Condicoes de Pagamento',default=1,choices=CONDICOES_PAGTO_CHOICES)
    valor_imovel = models.DecimalField(verbose_name='Valor do Imovel',max_digits=10, decimal_places=2)
    valor_comissao = models.DecimalField(verbose_name='Comissao', max_digits=10, decimal_places=2)
    
    class Meta():
        ordering = ('vendedor','data_inclusao',)

    def __str__(self) -> str:
        return str(self.id)

vendedor/models.py
from django.contrib.auth.models import AbstractUser

class Vendedor(AbstractUser):
    pass

cliente/views.py
from django.shortcuts import render

# Create your views here.

imovel/views.py
from django.shortcuts import render

# Create your views here.

pages/views.py
from django.views.generic import TemplateView, View
from django.shortcuts import HttpResponse, render, reverse
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from imovel.models import Imovel
from cliente.models import Cliente
from venda.models import CONDICOES_PAGTO_CHOICES, Venda

from django.contrib.auth.mixins import LoginRequiredMixin


class HomePageView(LoginRequiredMixin, TemplateView):
    login_url = '/admin/login/'
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['imoveis'] = Imovel.available.all()
        return context

class VendaPageView(LoginRequiredMixin,View):
    login_url = '/admin/login/'
    template_name = 'venda.html'

    def get(self, request, id_imovel:int):
        
        try:
            imovel = Imovel.available.get_by_id(id_imovel)
        except Imovel.DoesNotExist as e:
            return HttpResponseNotFound('Imovel não encontrado')
        
        clientes = Cliente.available.all()

        return render(request, self.template_name, {
            'imovel': imovel,
            'condicoes_pagto': CONDICOES_PAGTO_CHOICES,
            'clientes': clientes
        })

    def post(self, request, id_imovel:int):

        id_cliente = request.POST.get('cliente_id')
        condicao_pagto = int(request.POST.get('condicao_pagto'))
        valor_imovel = request.POST.get('valor_imovel')
        valor_comissao = request.POST.get('comissao')

        if id_cliente is None:
            return HttpResponseNotFound('Voce precisa fornecer um cliente')

        try:
            imovel = Imovel.available.get_by_id(id_imovel)
        except Imovel.DoesNotExist as e:
            return HttpResponseNotFound('Imovel não encontrado')

        try:
            cliente = Cliente.available.get_by_id(int(id_cliente))
        except Cliente.DoesNotExist:
            return HttpResponseNotFound('Cliente não existe')

        venda = Venda()
        venda.imovel = imovel
        venda.cliente = cliente
        venda.vendedor = request.user
        venda.condicao_pagto = condicao_pagto
        venda.valor_imovel = float(valor_imovel.replace(',','.'))
        venda.valor_comissao = float(valor_comissao.replace(',','.'))
        venda.save()

        return HttpResponseRedirect(
            reverse('pages:relatorio', args=(venda.id, ))
        )


class RelatorioPageView(LoginRequiredMixin,View):
    login_url = '/admin/login/'
    template_name = 'relatorio.html'

    def get(self, request, id_venda:int):
        
        try:
            venda = Venda.objects.filter(id=id_venda).get()
        except Venda.DoesNotExist:
            return HttpResponseNotFound('Venda não encontrada')
        
        return render(request, self.template_name, {
            'venda': venda
        })

vendedor/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Venda de Imoveis</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
    <script src="https://kit.fontawesome.com/8111ef0cbd.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static '/blog/style.css' %}">
    {% block extra_header %}
    {% endblock %}
  </head>
  <body>
    <div>
      {% include "includes/header.html" %}
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
<section class="section">
  <div class="container">
    <div class="columns is-flex">
      <div class="column">
        <h3 class="subtitle is-3">Selecione o Imovel/Lote</h3>
      </div>
      <div class="select">
        <select name='tipo'>
          <option>Todos</option>
          <option>Apartamento</option>
          <option>Lote</option>
        </select>
      </div>
    </div>

      {% for imovel in imoveis %}
      <div class="card mx-6 mt-4">
        <div class="card-content ">
          <div class="media">
            <div class="media-content">
              <a href="{% url 'pages:venda' imovel.id %}">
                <p class="title is-4">{{imovel.id}} - {{imovel.descricao}}</p>
              </a>
              <p class="subtitle is-6">{{imovel.endereco}}</p>
            </div>
          </div>
  
          <h6 class="title is-6 ">Valor do Imovel</h6>
          <h6 class="subtitle is-6 mx-4">{{imovel.valor_imovel}}</h6>
  
          <h6 class="title is-6">Comissao</h6>
          <h6 class="subtitle is-6 mx-4">{{imovel.comissao}}</h6>
  
          <h6 class="title is-6">Tipo</h6>
          <h6 class="subtitle is-6 mx-4">{{imovel.tipo}}</h6>

          <br/>
          <footer class="card-footer">
            <p class="card-footer-item">Publicado em {{imovel.data_inclusao}}</p>
          </footer>
        </div>
      </div>
      {% endfor %}
  </div>
</section>
{% endblock %}

templates/includes/header.html
<header></header>
  <section class="hero is-info">
    <div class="hero-body has-text-centered">
      <p class="title">
        Venda de Imoveis
      </p>

      <a href="{% url 'admin:index' %}">Voltar ao Administrativo</a>
      <p>Logado como: {{ request.user }}</p>
    </div>
  </section>
  </header>

templates/includes/login.html
{% extends 'base.html' %}
{% block title %} Login {% endblock %}

{% block content %}

<h1>login</h1>
<br/><br/>

<div class="form-group">
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-secondaray" ></button>
    </form>
</div>
{% endblock %}

templates/relatorio.html
{% extends 'base.html' %}

{% block content %}

<section class="section">
    <h1>Relatório da venda</h1>
    
    <table class="table">
        <thead>
          <tr>
            <th><abbr title="Position">Imovel</abbr></th>
            <th>Vendedor</th>
            <th><abbr title="Played">Cliente</abbr></th>
            <th><abbr title="Won">Condição de pagamento</abbr></th>
            <th><abbr title="Drawn">valor do Imovel</abbr></th>
            <th><abbr title="Drawn">comissao</abbr></th>
            <th><abbr title="Drawn">Data venda</abbr></th>
          </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{venda.imovel}}</td>
                <td>{{venda.vendedor}}</td>
                <td>{{venda.cliente}}</td>
                <td>{{venda.condicao_pagto}}</td>
                <td>{{venda.valor_imovel}}</td>
                <td>{{venda.valor_comissao}}</td>
                <td>{{venda.data_inclusao}}</td>
            </tr>
        </tbody>
      </table>

      <a href="{% url 'admin:venda_venda_change' venda %}">Veja detalhes no painel administrativo</a>

</section>
{% endblock %}

templates/venda.html
{% extends 'base.html' %}
{% block content %}
<section class="section">
  <form method="post" action="">
    {% csrf_token %}
  <div class="card mx-6 mt-4">
    <div class="columns">
      <div class="column">
        <div class="card-content ">
          <div class="media">
            <div class="media-content">
              <p class="title is-4">{{imovel.descricao}}</p>
              <p class="subtitle is-6">{{imovel.endereco}}</p>
            </div>
          </div>
        
          <h6 class="title is-6 ">Valor do Imovel</h6>
          <!-- <h6 class="subtitle is-6 mx-4" >{{imovel.valor_imovel}}</h6> -->
            <input class="input is-6 mx-4" type="text" name='valor_imovel' value="{{ imovel.valor_imovel }}"></input>
        
          <h6 class="title is-6">Comissao</h6>
          <input class="input is-6 mx-4" type="text" name='comissao' value="{{ imovel.comissao }}"></input>
          <!-- <h6 class="subtitle is-6 mx-4">{{imovel.comissao}}</h6> -->
        
          <h6 class="title is-6">Tipo</h6>
          <h6 class="subtitle is-6 mx-4">{{imovel.tipo}}</h6>
        
          <br/>
        </div>
      </div>
      <div class="column">
        <p class="subtitle is-6 mt-5">Pagamento</p>
        <div class="select">
          <select name='condicao_pagto'>
            {% for item in condicoes_pagto%}
              <option value="{{ item.0 }}">{{ item.1 }}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="column">
        <p class="subtitle is-6 mt-5">Cliente</p>
        <div class="select">
          <select name='cliente_id'>
            {% for cliente in clientes %}
            <option value="{{ cliente.id }}">{{ cliente.nome }}</option>
            {% endfor %}
          </select>
        </div>
        
      </div>
    </div>
    <footer class="card-footer">
      <button type="submit" class="button is-info is-rounded">Finalizar</button>
    </footer>
  </div>
  </form>
</section>
{% endblock %}